server:
  port: 8082

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientAuthenticationScheme: form
      scope: server
    resource:
      userInfoUri: http://localhost:8080/user/info
      preferTokenInfo: false

